package astro.tool.box.enumeration;

public enum Epoch {

    ALL,
    ALL_ASCENDING,
    ALL_DESCENDING,
    ALL_ASCENDING_ALL_DESCENDING,
    YEAR,
    FIRST_REMAINING,
    FIRST_REMAINING_PARALLAX,
    FIRST_REMAINING_SUBTRACTED,
    FIRST_LAST,
    FIRST_LAST_PARALLAX,
    FIRST_LAST_SUBTRACTED

}
