package astro.tool.box.enumeration;

public enum Epoch {

    ALL,
    ASCENDING,
    DESCENDING,
    ASCENDING_DESCENDING,
    ASCENDING_DESCENDING_SUBTRACTED,
    ASCENDING_DESCENDING_PARALLAX,
    YEAR,
    FIRST_REMAINING,
    FIRST_REMAINING_SUBTRACTED,
    FIRST_LAST,
    FIRST_LAST_SUBTRACTED,
    FIRST_LAST_PARALLAX,

}
